import type { Restaurant, Review, Promotion, MenuItem, City, Category } from "@/types/restaurant"

// Datos de ciudades
export const mockCities: City[] = [
  {
    id: "1",
    name: "Cancún",
    slug: "cancun",
    state: "Quintana Roo",
    restaurantCount: 12,
  },
  {
    id: "2",
    name: "Playa del Carmen",
    slug: "playa-del-carmen",
    state: "Quintana Roo",
    restaurantCount: 8,
  },
  {
    id: "3",
    name: "Mérida",
    slug: "merida",
    state: "Yucatán",
    restaurantCount: 15,
  },
  {
    id: "4",
    name: "Puerto Vallarta",
    slug: "puerto-vallarta",
    state: "Jalisco",
    restaurantCount: 10,
  },
]

// Datos de categorías
export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Mariscos",
    slug: "mariscos",
    description: "Restaurantes especializados en mariscos y pescados frescos del Caribe y Pacífico mexicano",
  },
  {
    id: "2",
    name: "Comida Mexicana",
    slug: "comida-mexicana",
    description: "Auténtica cocina mexicana tradicional con recetas ancestrales y sabores regionales",
  },
  {
    id: "3",
    name: "Internacional",
    slug: "internacional",
    description: "Cocina internacional y fusión con influencias de todo el mundo",
  },
  {
    id: "4",
    name: "Buffet",
    slug: "buffet",
    description: "Restaurantes tipo buffet con gran variedad de platillos para todos los gustos",
  },
  {
    id: "5",
    name: "Desayunos",
    slug: "desayunos",
    description: "Especialistas en desayunos, brunch y comidas matutinas",
  },
  {
    id: "6",
    name: "Café y Postres",
    slug: "cafe-postres",
    description: "Cafeterías, reposterías y lugares especializados en postres artesanales",
  },
]

// Datos de promociones
export const mockPromotions: Promotion[] = [
  {
    id: "1",
    title: "2x1 en cervezas",
    description: "Válido de lunes a viernes de 5pm a 7pm. No aplica en días festivos.",
    validUntil: "2024-12-31",
    isActive: true,
  },
  {
    id: "2",
    title: "Ceviche gratis",
    description: "Con consumo mínimo de $800 pesos. Una orden de ceviche mixto por mesa.",
    validUntil: "2024-12-31",
    isActive: true,
  },
  {
    id: "3",
    title: "Martes de mariscos",
    description: "20% de descuento en todos los platillos de mariscos los días martes.",
    validUntil: "2024-12-31",
    isActive: true,
  },
  {
    id: "4",
    title: "Combo familiar",
    description: "4 órdenes de tacos + 2 sopas de lima + 4 aguas frescas por $350 pesos.",
    validUntil: "2024-12-31",
    isActive: true,
  },
  {
    id: "5",
    title: "Happy hour",
    description: "Micheladas y cervezas 2x1 de 4pm a 6pm todos los días.",
    validUntil: "2024-12-31",
    isActive: true,
  },
  {
    id: "6",
    title: "Noche romántica",
    description: "Cena para 2 personas con botella de vino incluida por $1,200 pesos.",
    validUntil: "2024-12-31",
    isActive: true,
  },
  {
    id: "7",
    title: "Desayuno completo",
    description: "Café americano gratis con cualquier desayuno de lunes a viernes.",
    validUntil: "2024-12-31",
    isActive: true,
  },
]

// Datos de elementos del menú
export const mockMenuItems: MenuItem[] = [
  // La Pescadería del Puerto
  {
    id: "1",
    name: "Ceviche Mixto",
    description: "Pescado blanco, camarón y pulpo marinado en limón con cebolla morada, cilantro y chile habanero",
    price: 180,
    category: "Entradas",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "2",
    name: "Aguachile Verde",
    description: "Camarones frescos en salsa verde picante con pepino, cebolla y aguacate",
    price: 220,
    category: "Entradas",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "3",
    name: "Pescado a la Parrilla",
    description: "Mero fresco a la parrilla con guarnición de verduras asadas y arroz blanco",
    price: 320,
    category: "Platos Fuertes",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "4",
    name: "Langosta Termidor",
    description: "Langosta gratinada con queso, mantequilla, especias y un toque de brandy",
    price: 650,
    category: "Platos Fuertes",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "5",
    name: "Sopa de Mariscos",
    description: "Caldo concentrado con mariscos mixtos, verduras y un toque de epazote",
    price: 280,
    category: "Sopas",
    image: "/placeholder.svg?height=200&width=300",
  },
  // Mariscos El Capitán
  {
    id: "6",
    name: "Coctel de Camarón",
    description: "Camarones cocidos con salsa especial de la casa, aguacate y galletas saladas",
    price: 120,
    category: "Entradas",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "7",
    name: "Pulpo a las Brasas",
    description: "Pulpo tierno asado a las brasas con ajo, hierbas finas y aceite de oliva",
    price: 180,
    category: "Platos Fuertes",
    image: "/placeholder.svg?height=200&width=300",
  },
  // Tacos El Fogón Maya
  {
    id: "8",
    name: "Tacos de Cochinita Pibil",
    description: "Orden de 4 tacos con cochinita pibil, cebolla morada encurtida y salsa habanera",
    price: 85,
    category: "Tacos",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "9",
    name: "Sopa de Lima",
    description: "Tradicional sopa yucateca con pollo deshebrado, lima agria y tortilla frita",
    price: 65,
    category: "Sopas",
    image: "/placeholder.svg?height=200&width=300",
  },
  // Da Vinci
  {
    id: "10",
    name: "Carpaccio di Manzo",
    description: "Láminas de res cruda con rúcula, parmesano, alcaparras y aceite de oliva extra virgen",
    price: 280,
    category: "Entradas",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "11",
    name: "Pizza Margherita",
    description: "Pizza tradicional con salsa de tomate San Marzano, mozzarella di bufala y albahaca fresca",
    price: 250,
    category: "Pizzas",
    image: "/placeholder.svg?height=200&width=300",
  },
]

// Datos de reseñas
export const mockReviews: Review[] = [
  {
    id: "1",
    userId: "user1",
    userName: "María González",
    userAvatar: "/placeholder.svg?height=40&width=40",
    restaurantId: "1",
    rating: 5,
    comment:
      "Excelente experiencia! El ceviche estaba fresco y delicioso. El servicio fue muy atento y la vista al mar es espectacular. Definitivamente regresaremos para probar más platillos. La langosta termidor es imperdible.",
    images: ["/placeholder.svg?height=200&width=200"],
    createdAt: "2024-01-15T19:30:00Z",
    ownerResponse: {
      message:
        "¡Muchas gracias María! Nos da mucho gusto saber que disfrutaron su visita. Los esperamos pronto para que prueben nuestros nuevos platillos de temporada.",
      createdAt: "2024-01-16T10:15:00Z",
    },
  },
  {
    id: "2",
    userId: "user2",
    userName: "Carlos Mendoza",
    userAvatar: "/placeholder.svg?height=40&width=40",
    restaurantId: "1",
    rating: 4,
    comment:
      "Muy buena comida y ambiente familiar. Los precios son justos para la calidad que ofrecen. Recomiendo el pescado a la parrilla, estaba en su punto perfecto. El único detalle es que tardaron un poco en servir.",
    images: [],
    createdAt: "2024-01-10T20:45:00Z",
  },
  {
    id: "3",
    userId: "user3",
    userName: "Ana Rodríguez",
    userAvatar: "/placeholder.svg?height=40&width=40",
    restaurantId: "1",
    rating: 5,
    comment:
      "La langosta termidor es increíble! El lugar tiene una vista hermosa y el personal es muy profesional. Vale la pena cada peso. Perfecto para una cena romántica o celebración especial.",
    images: ["/placeholder.svg?height=200&width=200"],
    createdAt: "2024-01-08T21:20:00Z",
  },
  {
    id: "4",
    userId: "user4",
    userName: "Roberto Silva",
    userAvatar: "/placeholder.svg?height=40&width=40",
    restaurantId: "2",
    rating: 4,
    comment:
      "Lugar tradicional con sabores auténticos. El coctel de camarón es de los mejores que he probado en Cancún. Precios muy accesibles y porciones generosas. Ambiente familiar muy agradable.",
    images: [],
    createdAt: "2024-01-12T18:15:00Z",
  },
  {
    id: "5",
    userId: "user5",
    userName: "Diego Morales",
    userAvatar: "/placeholder.svg?height=40&width=40",
    restaurantId: "3",
    rating: 5,
    comment:
      "Los mejores tacos de cochinita pibil de Cancún! La sopa de lima también está deliciosa. Muy auténtico, se nota que siguen las recetas tradicionales yucatecos. Precios súper accesibles.",
    images: ["/placeholder.svg?height=200&width=200"],
    createdAt: "2024-01-14T13:30:00Z",
  },
  {
    id: "6",
    userId: "user6",
    userName: "Isabella Rossi",
    userAvatar: "/placeholder.svg?height=40&width=40",
    restaurantId: "4",
    rating: 5,
    comment:
      "Auténtica cocina italiana en Cancún. El chef realmente sabe lo que hace, la pasta está hecha en casa y se nota la calidad. Perfecto para una cena romántica con vista a la laguna.",
    images: [],
    createdAt: "2024-01-11T20:00:00Z",
  },
]

// Datos de restaurantes
export const mockRestaurants: Restaurant[] = [
  {
    id: "1",
    name: "La Pescadería del Puerto",
    slug: "la-pescaderia-del-puerto",
    tagline: "Mariscos frescos con vista al mar",
    description:
      "Restaurante familiar especializado en mariscos y pescados frescos, con más de 20 años de tradición culinaria en Cancún. Ofrecemos los mejores ceviches, pescados a la parrilla y mariscos preparados con ingredientes locales de la más alta calidad. Nuestro chef ejecutivo, con experiencia en cocina costera, crea platillos que combinan técnicas tradicionales mexicanas con toques contemporáneos. El ambiente relajado y la vista panorámica al mar Caribe hacen de cada comida una experiencia memorable.",
    category: "mariscos",
    subcategory: "mariscos-gourmet",
    city: "cancun",
    state: "Quintana Roo",
    address: "Blvd. Kukulcán Km 9.5, Zona Hotelera, 77500 Cancún, Q.R.",
    coordinates: {
      lat: 21.1619,
      lng: -86.8515,
    },
    googleMapsLink: "https://maps.google.com/?q=21.1619,-86.8515",
    rating: 4.5,
    reviewCount: 324,
    priceRange: "mid",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    categorizedImages: {
      interior: { url: "/placeholder.svg?height=200&width=200", count: 77 },
      food: { url: "/placeholder.svg?height=200&width=200", count: 466 },
      menu: { url: "/placeholder.svg?height=200&width=200", count: 9 },
      all: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
      ],
    },
    amenities: [
      "Vista al mar",
      "Aire acondicionado",
      "Acepta tarjetas",
      "Estacionamiento",
      "WiFi gratuito",
      "Pet friendly",
      "Terraza",
      "Bar completo",
      "Música en vivo",
    ],
    promotions: [mockPromotions[0], mockPromotions[1]],
    menu: [mockMenuItems[0], mockMenuItems[1], mockMenuItems[2], mockMenuItems[3], mockMenuItems[4]],
    hours: {
      lun: { open: "12:00", close: "22:00", isClosed: false },
      mar: { open: "12:00", close: "22:00", isClosed: false },
      mie: { open: "12:00", close: "22:00", isClosed: false },
      jue: { open: "12:00", close: "22:00", isClosed: false },
      vie: { open: "12:00", close: "23:00", isClosed: false },
      sab: { open: "12:00", close: "23:00", isClosed: false },
      dom: { open: "12:00", close: "21:00", isClosed: false },
    },
    isOpen: true,
    isClaimed: true,
    ownerId: "owner1",
    ranking: { position: 15, total: 200 },
    dietaryOptions: ["Apto para vegetarianos", "Opciones veganas"],
  },
  {
    id: "2",
    name: "Mariscos El Capitán",
    slug: "mariscos-el-capitan",
    tagline: "Tradición marinera desde 1985",
    description:
      "Auténticos mariscos preparados con recetas tradicionales de la costa de Yucatán. Especialistas en cocteles de camarón, pulpo a las brasas y pescado frito estilo Campeche. Un lugar familiar con ambiente casual y precios accesibles. Don Raúl, el capitán fundador, sigue supervisando personalmente la selección de mariscos frescos cada mañana en el mercado local. La sazón casera y las porciones generosas han convertido a este lugar en un favorito de locales y turistas por igual.",
    category: "mariscos",
    subcategory: "mariscos-tradicionales",
    city: "cancun",
    state: "Quintana Roo",
    address: "Av. Tulum 145, Centro, 77500 Cancún, Q.R.",
    coordinates: {
      lat: 21.1743,
      lng: -86.8466,
    },
    googleMapsLink: "https://maps.google.com/?q=21.1743,-86.8466",
    rating: 4.2,
    reviewCount: 156,
    priceRange: "budget",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    categorizedImages: {
      interior: { url: "/placeholder.svg?height=200&width=200", count: 30 },
      food: { url: "/placeholder.svg?height=200&width=200", count: 120 },
      menu: { url: "/placeholder.svg?height=200&width=200", count: 5 },
      all: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
      ],
    },
    amenities: [
      "Estacionamiento",
      "WiFi gratuito",
      "Terraza",
      "Acepta efectivo",
      "Ambiente familiar",
      "Comida para llevar",
      "Precios accesibles",
    ],
    promotions: [mockPromotions[2]],
    menu: [mockMenuItems[5], mockMenuItems[6]],
    hours: {
      lun: { open: "11:00", close: "21:00", isClosed: false },
      mar: { open: "11:00", close: "21:00", isClosed: false },
      mie: { open: "11:00", close: "21:00", isClosed: false },
      jue: { open: "11:00", close: "21:00", isClosed: false },
      vie: { open: "11:00", close: "22:00", isClosed: false },
      sab: { open: "11:00", close: "22:00", isClosed: false },
      dom: { open: "11:00", close: "20:00", isClosed: false },
    },
    isOpen: true,
    isClaimed: false,
    ranking: { position: 31, total: 94 },
    dietaryOptions: ["Opciones sin gluten"],
  },
  {
    id: "3",
    name: "Tacos El Fogón Maya",
    slug: "tacos-el-fogon-maya",
    tagline: "Auténticos sabores yucatecos",
    description:
      "Taquería tradicional especializada en cochinita pibil, sopa de lima y otros platillos típicos de Yucatán. Preparamos todo en horno de leña siguiendo recetas ancestrales mayas. El lugar perfecto para conocer la verdadera comida yucateca. Doña Carmen, originaria de Valladolid, Yucatán, trajo consigo las recetas familiares que han pasado de generación en generación. El achiote se muele diariamente y la cochinita se cocina lentamente en hojas de plátano para lograr ese sabor único e inigualable.",
    category: "comida-mexicana",
    subcategory: "cocina-yucateca",
    city: "cancun",
    state: "Quintana Roo",
    address: "Av. Yaxchilán 31, SM 22, 77500 Cancún, Q.R.",
    coordinates: {
      lat: 21.1611,
      lng: -86.8312,
    },
    googleMapsLink: "https://maps.google.com/?q=21.1611,-86.8312",
    rating: 4.7,
    reviewCount: 892,
    priceRange: "budget",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    categorizedImages: {
      interior: { url: "/placeholder.svg?height=200&width=200", count: 50 },
      food: { url: "/placeholder.svg?height=200&width=200", count: 300 },
      menu: { url: "/placeholder.svg?height=200&width=200", count: 12 },
      all: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
      ],
    },
    amenities: [
      "Comida para llevar",
      "Entrega a domicilio",
      "Acepta efectivo",
      "Ambiente casual",
      "Especialidad regional",
      "Horno de leña",
      "Recetas ancestrales",
    ],
    promotions: [mockPromotions[3], mockPromotions[4]],
    menu: [mockMenuItems[7], mockMenuItems[8]],
    hours: {
      lun: { open: "08:00", close: "23:00", isClosed: false },
      mar: { open: "08:00", close: "23:00", isClosed: false },
      mie: { open: "08:00", close: "23:00", isClosed: false },
      jue: { open: "08:00", close: "23:00", isClosed: false },
      vie: { open: "08:00", close: "24:00", isClosed: false },
      sab: { open: "08:00", close: "24:00", isClosed: false },
      dom: { open: "08:00", close: "22:00", isClosed: false },
    },
    isOpen: true,
    isClaimed: true,
    ranking: { position: 5, total: 200 },
    dietaryOptions: ["Opciones vegetarianas", "Opciones sin lácteos"],
  },
  {
    id: "4",
    name: "Restaurante Italiano Da Vinci",
    slug: "restaurante-italiano-da-vinci",
    tagline: "Auténtica cocina italiana en el Caribe",
    description:
      "Elegante restaurante italiano con chef napolitano. Especialistas en pasta fresca hecha en casa, pizzas en horno de leña y una selecta carta de vinos italianos. Ambiente romántico perfecto para cenas especiales con vista a la laguna. El Chef Giuseppe, originario de Nápoles, trajo consigo 25 años de experiencia en cocina italiana tradicional. Cada pasta se prepara fresca diariamente y nuestro horno de leña importado de Italia garantiza pizzas con la auténtica textura y sabor napolitano.",
    category: "internacional",
    subcategory: "cocina-italiana",
    city: "cancun",
    state: "Quintana Roo",
    address: "Blvd. Kukulcán Km 14.2, Zona Hotelera, 77500 Cancún, Q.R.",
    coordinates: {
      lat: 21.0845,
      lng: -86.8234,
    },
    googleMapsLink: "https://maps.google.com/?q=21.0845,-86.8234",
    rating: 4.6,
    reviewCount: 267,
    priceRange: "premium",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    categorizedImages: {
      interior: { url: "/placeholder.svg?height=200&width=200", count: 60 },
      food: { url: "/placeholder.svg?height=200&width=200", count: 250 },
      menu: { url: "/placeholder.svg?height=200&width=200", count: 15 },
      all: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
      ],
    },
    amenities: [
      "Vista a la laguna",
      "Aire acondicionado",
      "Valet parking",
      "Bar completo",
      "Música en vivo",
      "Reservaciones",
      "Dress code",
      "Cava de vinos",
      "Terraza romántica",
    ],
    promotions: [mockPromotions[5]],
    menu: [mockMenuItems[9], mockMenuItems[10]],
    hours: {
      lun: { open: "17:00", close: "23:00", isClosed: false },
      mar: { open: "17:00", close: "23:00", isClosed: false },
      mie: { open: "17:00", close: "23:00", isClosed: false },
      jue: { open: "17:00", close: "23:00", isClosed: false },
      vie: { open: "17:00", close: "24:00", isClosed: false },
      sab: { open: "17:00", close: "24:00", isClosed: false },
      dom: { open: "17:00", close: "22:00", isClosed: false },
    },
    isOpen: true,
    isClaimed: true,
    ranking: { position: 10, total: 200 },
    dietaryOptions: ["Opciones sin gluten", "Opciones vegetarianas"],
  },
  {
    id: "5",
    name: "Café Nader",
    slug: "cafe-nader",
    tagline: "Desayunos y café de especialidad",
    description:
      "Acogedora cafetería en el corazón del centro de Cancún. Famosos por nuestros desayunos tradicionales mexicanos, café de altura de Chiapas y repostería artesanal. El lugar perfecto para comenzar el día o tomar un break del shopping. Nuestro café proviene directamente de pequeños productores de Chiapas, tostado artesanalmente cada semana. La repostería se prepara diariamente en nuestro obrador, utilizando ingredientes locales como miel de abeja melipona y vainilla de Papantla.",
    category: "cafe-postres",
    subcategory: "cafeteria-artesanal",
    city: "cancun",
    state: "Quintana Roo",
    address: "Av. Nader 5, Centro, 77500 Cancún, Q.R.",
    coordinates: {
      lat: 21.1619,
      lng: -86.8515,
    },
    googleMapsLink: "https://maps.google.com/?q=21.1619,-86.8515",
    rating: 4.3,
    reviewCount: 445,
    priceRange: "budget",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    categorizedImages: {
      interior: { url: "/placeholder.svg?height=200&width=200", count: 40 },
      food: { url: "/placeholder.svg?height=200&width=200", count: 180 },
      menu: { url: "/placeholder.svg?height=200&width=200", count: 7 },
      all: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
      ],
    },
    amenities: [
      "WiFi gratuito",
      "Aire acondicionado",
      "Terraza",
      "Café de especialidad",
      "Repostería artesanal",
      "Desayunos todo el día",
      "Ambiente acogedor",
      "Ideal para trabajar",
    ],
    promotions: [mockPromotions[6]],
    menu: [],
    hours: {
      lun: { open: "07:00", close: "15:00", isClosed: false },
      mar: { open: "07:00", close: "15:00", isClosed: false },
      mie: { open: "07:00", close: "15:00", isClosed: false },
      jue: { open: "07:00", close: "15:00", isClosed: false },
      vie: { open: "07:00", close: "16:00", isClosed: false },
      sab: { open: "08:00", close: "16:00", isClosed: false },
      dom: { open: "08:00", close: "14:00", isClosed: false },
    },
    isOpen: true,
    isClaimed: false,
    ranking: { position: 25, total: 200 },
    dietaryOptions: ["Opciones sin gluten", "Opciones veganas"],
  },
  // Restaurantes adicionales para tener más variedad
  {
    id: "6",
    name: "Sushi Zen",
    slug: "sushi-zen",
    tagline: "Auténtica experiencia japonesa",
    description:
      "Restaurante japonés auténtico con sushi chef certificado de Tokio. Ingredientes frescos importados y técnicas tradicionales japonesas. Ambiente zen con decoración minimalista y vista al jardín japonés. Nuestro chef Takeshi cuenta con 15 años de experiencia en Japón y utiliza únicamente pescado de la más alta calidad, importado diariamente desde Tsukiji.",
    category: "internacional",
    subcategory: "cocina-japonesa",
    city: "cancun",
    state: "Quintana Roo",
    address: "Av. Bonampak 145, SM 4, 77500 Cancún, Q.R.",
    coordinates: {
      lat: 21.165,
      lng: -86.835,
    },
    rating: 4.8,
    reviewCount: 189,
    priceRange: "premium",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    categorizedImages: {
      interior: { url: "/placeholder.svg?height=200&width=200", count: 55 },
      food: { url: "/placeholder.svg?height=200&width=200", count: 320 },
      menu: { url: "/placeholder.svg?height=200&width=200", count: 10 },
      all: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
      ],
    },
    amenities: [
      "Sushi bar",
      "Jardín japonés",
      "Sake premium",
      "Chef certificado",
      "Ambiente zen",
      "Reservaciones",
      "Ingredientes importados",
    ],
    promotions: [],
    menu: [],
    hours: {
      lun: { open: "18:00", close: "23:00", isClosed: false },
      mar: { open: "18:00", close: "23:00", isClosed: false },
      mie: { open: "18:00", close: "23:00", isClosed: false },
      jue: { open: "18:00", close: "23:00", isClosed: false },
      vie: { open: "18:00", close: "24:00", isClosed: false },
      sab: { open: "18:00", close: "24:00", isClosed: false },
      dom: { open: "18:00", close: "22:00", isClosed: false },
    },
    isOpen: true,
    isClaimed: true,
    ranking: { position: 8, total: 200 },
    dietaryOptions: ["Opciones sin gluten"],
  },
  {
    id: "7",
    name: "La Parrilla Mexicana",
    slug: "la-parrilla-mexicana",
    tagline: "Carnes y parrilladas al carbón",
    description:
      "Especialistas en carnes a la parrilla y cortes premium. Ambiente ranchero mexicano con mariachi en vivo los fines de semana. Nuestra parrilla de carbón y nuestros cortes de res angus garantizan una experiencia gastronómica única. El ambiente festivo y la música tradicional mexicana crean el escenario perfecto para celebraciones familiares.",
    category: "comida-mexicana",
    subcategory: "parrilladas",
    city: "cancun",
    state: "Quintana Roo",
    address: "Av. Yaxchilán 61, SM 22, 77500 Cancún, Q.R.",
    coordinates: {
      lat: 21.158,
      lng: -86.829,
    },
    rating: 4.4,
    reviewCount: 567,
    priceRange: "mid",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    categorizedImages: {
      interior: { url: "/placeholder.svg?height=200&width=200", count: 90 },
      food: { url: "/placeholder.svg?height=200&width=200", count: 400 },
      menu: { url: "/placeholder.svg?height=200&width=200", count: 18 },
      all: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
        "/placeholder.svg?height=300&width=400",
      ],
    },
    amenities: [
      "Parrilla al carbón",
      "Mariachi en vivo",
      "Ambiente festivo",
      "Cortes premium",
      "Bar de tequilas",
      "Estacionamiento",
      "Grupos grandes",
    ],
    promotions: [],
    menu: [],
    hours: {
      lun: { open: "13:00", close: "23:00", isClosed: false },
      mar: { open: "13:00", close: "23:00", isClosed: false },
      mie: { open: "13:00", close: "23:00", isClosed: false },
      jue: { open: "13:00", close: "23:00", isClosed: false },
      vie: { open: "13:00", close: "24:00", isClosed: false },
      sab: { open: "13:00", close: "24:00", isClosed: false },
      dom: { open: "13:00", close: "22:00", isClosed: false },
    },
    isOpen: true,
    isClaimed: true,
    ranking: { position: 20, total: 200 },
    dietaryOptions: ["Opciones sin lácteos"],
  },
]

// Función para obtener amenidades únicas
export function getUniqueAmenities(): string[] {
  const amenitiesSet = new Set<string>()
  mockRestaurants.forEach((restaurant) => {
    restaurant.amenities.forEach((amenity) => amenitiesSet.add(amenity))
  })
  return Array.from(amenitiesSet).sort()
}
